version: '3.3'
services:
  server:
    image: tomcat:9-jre8
    ports:
      - "80:8080"
    logging:
      driver: json-file
    volumes:
      - /opt/tomcat/webapps/deploy.war:/usr/local/tomcat/webapps/deploy.war
    links:
      - db
  db:
    image: postgres:9.5
    ports:
      - "8888:5432"
    logging:
      driver: json-file
    environment:
      POSTGRES_PASSWORD: packt
      POSTGRES_USER: packt
      POSTGRES_DB: deploy
