image: ruby:2.6

variables:
  JEKYLL_ENV: production

before_script:
  - gem install bundle

stages:
  - build
  - test
  - deploy

test:
  stage: test
  script:
    - bundle exec jekyll doctor --config  _config.yml
  except:
    - master

build:
  stage: build
  script:
    - bundle install
    - bundle exec jekyll build -d static
  artifacts:
    paths:
      - static

pages:
  stage: deploy
  script:
    - mv static public
  artifacts:
    paths:
      - public
    expire_in: 1 day
